### ISSUE TITLE
cannot run rdsn on win7

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#114]
reported by @wangyan32

**Comment by imzhenyu** [comment]
I did not find a win7 machine but a server 2008 R2 which should use the same version of WINNT.

I did not reproduce the issue by the following steps:

git clone https://github.com/imzhenyu/rDSN.git
cd rDSN
git pull origin imzhenyu
git checkout imzhenyu
run build  Debug ./sln
run test Debug ./sln

**Comment by wangyan32** [comment]
the project: “dsn.core.test” works well on win7 platform, but the others works wrong, for example “dsn.tests”, “dsn.nfs.test”, etc..Did you try them on server2008 @imzhenyu, or the counter example?

**Comment by imzhenyu** [comment]
hi @wangyan32 no issues find on our machines. You may put dsn.core.dll together with your exe so things should be fine. Our latest run.cmd will automatically add $DSN_ROOT/lib to PATH so the dll will be automatically found. Hope this helps.

**Comment by imzhenyu** [comment]
@wangyan32 I've repeated this issue on a fresh machine now, hanged at 
if (!RegisterWaitForSingleObject(&m_hThrottlingWait, m_hThrottlingEvent, SchedulerBase::ThrottlerTrampoline, this, INFINITE, WT_EXECUTEDEFAULT))

We're looking into this for the root cause

**Comment by imzhenyu** [comment]
@wangyan32 seems to be a SDK bug that we cannot fix. We are changing the use of this though to avoid this bug. see pr at https://github.com/imzhenyu/rDSN/pull/127
