### ISSUE TITLE
add config.ini tool binary to get config.ini key value

### ISSUE THREAD

**Issue by goksyli** [imzhenyu/rDSN#118]
usage as this:
<configtool> <config file> <section> <key>
and it will put the key value if exists otherwise nothing

**Comment by goksyli** [comment]
done in #119 @imzhenyu please review

**Comment by imzhenyu** [comment]
@goksyli please also specify why this is needed, e.g. For what scenario.

**Comment by goksyli** [comment]
when publishing or deploying, we need to get which ports the program need to use. And our config.ini is not standard, which crash common ini parsers. All that makes it necessary to write a config getter using our library. Actually, I have discussed about this with you last Friday. @imzhenyu

**Comment by qinzuoyan** [comment]
I think it would be better to merge this tool into src/tools/repli, which is a integrated tool. Only using one tool will make life easier.

**Comment by imzhenyu** [comment]
@goksyli yes, we've discussed before, and let's document it here for others to understand why. @qinzuoyan this is good, and we can do it in our next round of refactoring.

**Comment by qinzuoyan** [comment]
as above, I merged configtool into tools/repli, because the old configtool may cause compile error on my machine
