### ISSUE TITLE
replica stub close hangs

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#133]
when a replica stub closes, there are chances where the closing is never done. The stack reveals that the problem is raised by the dsn_task_tracker_wait_all(xxx) line in mutation_log::close. A closer look into the waited task reports the task state is ready, indicating it has never been executed (or even enqueued). The config file used is vconfig.ini in simple-kv.

   // flush pending buffer first
    flush();

```
// make sure all issued aios are completed
dsn_task_tracker_wait_all(tracker());
```

**Comment by imzhenyu** [comment]
@glglwty a rough fix is in https://github.com/imzhenyu/rDSN/commit/6106a3c1d35b4456830022a25cabf11149f431a3  please review. and also, we may need to have two concurrent running mutation writes to bootstrap the mutation log throughput.

**Comment by glglwty** [comment]
I have no idea how your modification to flush() is fixing this issue.

**Comment by imzhenyu** [comment]
@glglwty it won't fix the hang - it fixes the missing issue_write that may cause learning holes. Let's continue digging the hang issue.

**Comment by imzhenyu** [comment]
the hang is caused by deadlock - LPC_WRITE_REPLICATION_LOG_FLUSH is dispatch to THREAD_POOL_REPLICATOIN_LONG, while close_replica is also done in the same pool which waits for the completion of LPC_WRITE_REPLICATION_LOG_FLUSH - easily leads to deadlock. Now we are moving LPC_WRITE_REPLICATION_LOG_FLUSH to default pool. Besides, we need to do two things: (1). automatically detect such deadlock on all waits;
(2). in the future, we should consider adopting user-level threading to avoid such deadlocks automatically (i.e., no blocking operations allowed).
