### ISSUE TITLE
fix private log data log bug caused by private batch writing and too fast garbage collection

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#135]
This problem is tricky. Because the private log is writing in batch mode, so the last buffer may have not been flushed into the file when servers core dump, which would cause log data lost. To ensure private log completeness, we need re-append mutations into private log when replaying shared logs on recovery. And:
- The lost data must exist in shared log
- The lost data should be re-append to private log when recovering.

So, we get:
- the condition of shared log GC: d <= last_durable_decree && d <= private_log.max_commit_decree
- the condition of re-append private log: d > private_log.max_commit_decree

So, we need to record the "private_log.max_commit_decree", which means the largest last_committed_decree in mutations which have been written into the private log. Also we need improve the shared log GC strategy the meet the above condition.

**Comment by qinzuoyan** [comment]
@imzhenyu , pls review it

**Comment by imzhenyu** [comment]
Good. As discussed, max_commit_decree is not enough, but max commit + disk written confirmed. You probably want to use max_on_disk_commit_decree etc. as the variable name.
