### ISSUE TITLE
latency in shared mutation log

### ISSUE THREAD

**Issue by glglwty** [imzhenyu/rDSN#175]
# problem

Currently in shared mutation_log, an append operation would dispatch a file::write if is_writing is false. For shared log, if it is delayed by is_writing and then the replica stopped doing init_prepare task, the shared log might never be written to the disk.
# possible fix

Bypass all the issued_write, pending_write stuff for shared log.
# discussion

The behavior of shared log and private log differs a lot. We could consider taking them apart into separate classes.

**Comment by imzhenyu** [comment]
Let's fix the perf issue first. Refactoring can be done later.
