### ISSUE TITLE
fix memory leak problem

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#207]
When doing perf test, we found obvious memory leak. So we should fix the problem by valgrind and windbg.

**Comment by glglwty** [comment]
It might be my last pull request that introduce memory leak. Let me reason about it. 
The reason might be circular reference in `safe_task`s. If that's the problem we might use strong/weak reference to address the problem.

**Comment by imzhenyu** [comment]
@glglwty I remember this case. Check the task_ptr inside mutation object, which also capture the mutation ptr inside them, leading to circular references. So we still need to nullify the closures to break the cycles.

**Comment by glglwty** [comment]
I'm analyzing memory allocation with some tools. So far I find nothing wrong.
Report:
https://gist.github.com/glglwty/fd766fa7cfe3d53deef3

**Comment by imzhenyu** [comment]
Thx Tianyi. note there is a "DecodeLeakResultsStack Failed!" at the end of the file, not sure it implies that the report is incomplete ...

**Comment by glglwty** [comment]
Here is another report.
https://gist.github.com/glglwty/f0ae047790303653c213

**Comment by imzhenyu** [comment]
The outstanding memory size is only around 52 MB. It is best if we can push the workload further which may make it easier for us to find the leaks (if exist).

**Comment by glglwty** [comment]
A 250MB one:
https://gist.github.com/glglwty/6f41567be7950b77e737

**Comment by imzhenyu** [comment]
We've looked into the memory leak problem again this morning with the version https://github.com/imzhenyu/rDSN/commit/8b936ea4c196dd7c54bd860611e0617439785a8c 
And we don't find leaks any more. 

Here are some scenarios that may allocate more memory but should not be considered memory leak.
- each thread has some tls buffer, e.g., transient memory, which allocates a 1-MB buffer on demand
- task queue contains many outstanding tasks - should wait for them being finished or the queue length being stable before measure the memory consumption
- outstanding timers - should wait them to be all finished before measurement. 

@qinzuoyan @shengofsun @xiaotz  If you are still experiencing memory leak, let us know and we can try here. 

Thx,
Zhenyu

**Comment by shengofsun** [comment]
Thx. We have recently tested the system on our server, the memory usage is indeed steady. So the memory leak I encountered before may be due to I didn't run the system for a long time.

**Comment by qinzuoyan** [comment]
cool~

**Comment by imzhenyu** [comment]
so we are good to close now :-) will open again if the issue surfaces later.
