### ISSUE TITLE
boost optional introduces unncessary dependency to the rdsn apps

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#211]
e.g., rrdb (replicated rocksdb) cannot compile now due to missing boost packages. We have to remove this dependency to avoid asking each rDSN user to install boost on their machines.

**Comment by qinzuoyan** [comment]
@glglwty , it seems your last commit to 'include/dsn/cpp/task_helper.h' brings in the "boost/optional.hpp", which makes rDSN header depending on boost. Would you remove the dependency?

**Comment by glglwty** [comment]
Yes, I will try to implement the same functionality within rDSN.

**Comment by imzhenyu** [comment]
fixed by @glglwty in https://github.com/imzhenyu/rDSN/pull/213
