### ISSUE TITLE
build.cmd in rdsn-python does not work for pip installation 

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#215]
The script does not install pip successfully, therefore the following required packages as well. Please fix and try on a clean machine.

**Comment by mcfatealan** [comment]
Ok, I'm downloading win10 iso on my mac, I'll try it when finished.

**Comment by imzhenyu** [comment]
@mcfatealan Thx, Chang.

**Comment by mcfatealan** [comment]
Fixed in https://github.com/mcfatealan/rDSN.Python/commit/e5342f06283a3bc1e96255673075fcca9e81f3dc 
Sorry for committing late. Network bandwidth at my home is much narrower than at MSRA. Everything takes a decade to download.
