### ISSUE TITLE
failure model for tcp network is incorrect

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#226]
Currently our fault injection simply drops messages for any network, which is however not necessarily right for certain networks, such as TCP. For example, we cannot drop one message but continue send the next correctly using one same tcp session.

**Comment by qinzuoyan** [comment]
So how should we do? just close the session?

**Comment by imzhenyu** [comment]
We will add a network specific callback and each network should implement their own failure model. i'm working on it. Specifically  for TCP, I think closing the socket to mimic network disconnection is fine.
