### ISSUE TITLE
auto generate replication.types.h from replication.thrift

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#227]
#### Problem

now the replication.types.h is modified from the one that is auto generated by replication.thrift, the problem is, if we add/modify some struct/interface in replication.thrift, then we need to copy code from generated replication.types.h, which is a boring and error-prone work.
#### Solution

just auto generate replication.types.h from replication.thrift, that means, we should not modify the generated replication.types.h, for example "mutation_data".

**Comment by glglwty** [comment]
We can do codegen at build time and remove all unmodified generated files from codebase.
