### ISSUE TITLE
support mutiple data directories and multiple devices

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#240]
#### Problem

In deploy environment, there are usually more than one storage devices, e.g., on our server, there are 8 ssd devices (each 0.8T). 

Now our system can only use one device in one process, we'd better improve the system to support mutiple data directories and multiple devices.

**Comment by imzhenyu** [comment]
Two ways: (1) data_dir to data_dirs[] in service spec; (2) customized configuration in each app. I think (2) is much simpler.

**Comment by qinzuoyan** [comment]
i think it is more complicated, discuss as:
- start more than one replica app in one process, and each replica app occupies a device
- start only one replica app in one process, and config data_dir to data_dirs[], and the replica_stub is responsible for distributing replicas to proper devices, considering storage space and load balance.

**Comment by imzhenyu** [comment]
I think starting one replica app is fine, and you can add more configurations such as replication-log-dir, replication-app-dirs.[] and use them in replica-stub.

**Comment by qinzuoyan** [comment]
sure, I am thinking about it, and the difficulty is using different data dirs for different replicas.

**Comment by qinzuoyan** [comment]
#### Resolution

In pr #246, I implemented a simple way to support separated slog_dir and multiple data_dirs as:
- add [replication].slog_dir config to specify shared log directory. The real used dir is:
  - if config[slog_dir] is empty: **_${app_dir}/slog**_
  - else: **_${config[slog_dir]}/${app_name}/slog**_
- add [replication].data_dirs config to specify replica data directories. The real used dirs are:
  - if config[data_dirs] is empty: **_${app_dir}/reps**_
  - else: **_${config[data_dirs][i]}/${app_name}/reps**_ for each item in config[data_dirs]

Replicas can be arranged among multiple directories in strategies such as "random" or "round robin". Currently we use **_round robin**_, please refer to replica_stub::get_replica_dir().
