### ISSUE TITLE
shared library initialization order problem

### ISSUE THREAD

**Issue by glglwty** [imzhenyu/rDSN#250]
Currently I cannot run simple_kv on linux at the point of ad1b1d3e7112cea6e0efa691ce46946e4e0cbf61. It seems that dsn_module_init of dsn.core.so (called by `__attribute__((constructor))`) is called before the static initialization of some custom_id (those objects is linked by `__attribute__((weak))`). I use gcc 4.8.4,glibc `EGLIBC 2.19-0ubuntu6.6` and it is 100% reproducible. It may be related to recent change of the factory of message parser. I do not know what is  exactly going on and is still investigating.

**Comment by shengofsun** [comment]
@glglwty this is because the bug of src/core/core/message_parser.cpp(line 102),  function message_parser_manager::message_parser_manager(), the resize should be max_value + 1. 
I've fixed

**Comment by glglwty** [comment]
right. It seems I was just wasting time.

**Comment by shengofsun** [comment]
Well, my time has been wasted on this T_T.
