### ISSUE TITLE
server load balancer will be adjusted contiguously when the cluster scales, better to make it pluggable

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#26]
TODO

**Comment by qinzuoyan** [comment]
When will we start the task? this task is not difficult, maybe we can finish it this week?

**Comment by imzhenyu** [comment]
np，I'm busy doing something else today, will do tomorrow.

**Comment by imzhenyu** [comment]
closed now, will be re-opened later on demand in later refactoring efforts.
