### ISSUE TITLE
latest version have mem leak again

### ISSUE THREAD

**Issue by xiaotz** [imzhenyu/rDSN#262]
commit: 123e930fd7faf41671a999c99f228b8aada8f25f

**Comment by imzhenyu** [comment]
@xiaotz can u illustrate how to repro the leak? Thx.

**Comment by xiaotz** [comment]
@imzhenyu I found that on our cluster using performance monitor provided by monitor.

I use 3 machines to form the replica group, each machine have 64G memory, 24 cpu cores. I create an app with 32 replicas and fill it with rrdb_bench tool, I found the latency increasing during data filling. and notice that there is a memory leak through our perf monitor. the memory usage is almost 64G on each machine.

will investigate more later.

**Comment by imzhenyu** [comment]
Thanks @xiaotz. Is the monitor you are using Xiaomi's internal tool or the one we provided in rDSN-Projects/rDSN.Python repo?

**Comment by xiaotz** [comment]
it an internal tool
