### ISSUE TITLE
rpc handler lookup using string is costly

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#279]
### Problem

In order to avoid inconsistent mappings from rpc string code to rpc interger code, we now always using rpc string code to look up rpc handler on server, which is costly. 
### Solution

when the client and server software are with the same version, this cost can be avoided. We therefore transmit binary hash and interger code as well in msg header, and use interger for rpc handler lookup when the client and the server have the same binary hash.

**Comment by imzhenyu** [comment]
fixed by #281

**Comment by shengofsun** [comment]
Bugs exist in this fix because the binary hash is generated when the compilation unit "rpc_message.cpp" is compiled, but not the executable binary is compiled. So different binaries may share the same hash if they link the same static/dynamic library.

**Comment by imzhenyu** [comment]
Nice catch. Thx so much, @shengofsun. Moreover, even the binary is the same, if they load different dynamic libraries which register more RPC codes, the mapping could be inconsistent.

Let's expose this to developers then, i.e., they can assign a binary hash (or a version with which same version implies the rpc message mapping is the same) to use this optimization. I'll come up a quick fix for this.

**Comment by qinzuoyan** [comment]
@imzhenyu , I think if the optimization is tricky and error-prone, is it better to remove the optimization?
In essence, if two binaries are the same, then we can use integer code directly. So the ideal binary hash is just hash of the binary file, but not generated at compile time. (Because task codes are assigned at runtime, but not at compile time)

**Comment by imzhenyu** [comment]
@qinzuoyan the problem is that even for the same binary, the mapping could be different, as they may load different versions of dynamic libraries which registers different rpc code. I think the optimization is worthwhile as long as we have the same binaries (including main executable and other dynamic libraries) & same configuration, which will be the common truth when deployed on production clusters. right?

**Comment by imzhenyu** [comment]
I'm c
