### ISSUE TITLE
FD beacon needs to have versions to avoid response out-dated messages

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#28]
TODO

**Comment by imzhenyu** [comment]
just go through the code and there is a time field which acts this role (to exclude out-dated acks). My bad memory. But the problem of the replication FD remains and I'll fix it soon.

**Comment by imzhenyu** [comment]
see pull request https://github.com/imzhenyu/rDSN/pull/49 @shengofsun @qinzuoyan please help review it.

**Comment by qinzuoyan** [comment]
ok, we'll review it. You'd better replace tab by spaces first.

**Comment by imzhenyu** [comment]
right, just set the tab options for my notepad++:)

**Comment by imzhenyu** [comment]
it is merged and test ok - I'm closing it now, and you may look into the pull request and share comments later.

**Comment by qinzuoyan** [comment]
Ok, we will look into it and add some test cases.

**Comment by imzhenyu** [comment]
yes, act scripts is not there yet, and the test is replying on those test cases. Currently, I don't do much test yet.
