### ISSUE TITLE
http header support in network

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#287]
Support http in all network providers by providing a new message parser that parses and composes http headers.

**Comment by imzhenyu** [comment]
@glglwty You may integrate the project from https://github.com/nodejs/http-parser as an external project to implement this.

**Comment by qinzuoyan** [comment]
@glglwty great work. And how can we use it? and unit-test?

**Comment by imzhenyu** [comment]
@qinzuoyan this work item needs to work together with #288, which enables htttp msg header and json msg body, together enabling so-called restful RPC. since #288 is not finished yet, we don't have unit-test yet.
