### ISSUE TITLE
support automatic data encoding/decoding using thrift in C++, C#, and Java

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#288]
### Problem
- Our http monitor requires json encoding/decoding of the TRequest/TResponse of rpc calls. 
- Our layer3 generate code in C#, which requires C# data encoding/decoding given a thrift idl file
### Solution

Let's get general support of TRequest/TResponse marshall/unmarshall for various languages (C++/C#/Java) and format (binary/binary-compact/JSON) with thrift.

**Comment by imzhenyu** [comment]
together with #287 , we can support http requests used by the http monitors running in browsers

**Comment by imzhenyu** [comment]
@ykwd You may look into protocs or bond as well, and you may prefer whichever seems simplest to implement first.

**Comment by imzhenyu** [comment]
pr from https://github.com/imzhenyu/rDSN/pull/308 also fixes this issue partially @shengofsun

**Comment by imzhenyu** [comment]
@ykwd , there are some problems with the latest layer 3 repo on my machine, please take a look:
- dsn.cmake 
  `message(FATAL_ERROR "thrift serialization currently only support Linux")`
   but we do support windows now, right?
- default configuration type is Win32 in VS solutions
  any changes to lead to this problem? 
- boost is now pulled everytime when we do the rebuild, which is too heavey. Note we already require boost being installed on local machine for rDSN, so it is unnecessary (apt-get on Linux and installed; wget on Windows and installed under rDSN/ext/).

**Comment by ykwd** [comment]
default configuration type is Win32 in VS solutions : This is indeed a problem. I will try to fix it.

boost : This problem has been solved with the recent 2 pr, which are still open.

dsn.cmake : oh, I see it. @shengofsun  has done something with thrift on Linux, when thrift is only available on Linux. Now thrift is available on Windows, and I am not sure if this is also work on his part on Windows.

**Comment by ykwd** [comment]
For the problem of default configuration type. It is said that cmake can't specify generator in CMakeLists.txt but can only specify it on cmd command, for example, with -G "Visual Studio 14 2015 Win64" (which is previously post on rdsn tutorial and is used in build.cmd), or with -DCMAKE_GENERATOR_PLATFORM "x64".
 So, @glglwty , if you use default cmake command to automatically build composite dlls, there might be potential risk.
This problem does not occur on Linux, since the default generator for a 64-bit Linux system is 64-bit.

**Comment by shengofsun** [comment]
@ykwd I've sent you an email to talk about the thrift problem a few days ago, but didn't get your reply. Maybe it is in your trash? 
In the layer3 branch, the thrift won't work on Linux either. And currently there are two files named "thrift_helper.h": "dsn/thrift_helper.h" and "dsn/idl/thrift_helper.h". And I guess the latter won't work fine.
Maybe we need a talk to deal with this.

**Comment by ykwd** [comment]
@shengofsun  sorry that I have neither found the email in my Inbox nor in my Junk-Email list. I notice that you have an account of Slack, can you receive my message on it?

**Comment by shengofsun** [comment]
@ykwd  i'm online now.

**Comment by shengofsun** [comment]
@ykwd  the slack website is blocked. Can we talk with skype(weijie_sun@hotmail.com)?
