### ISSUE TITLE
multi-node cli commands request and response manager support

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#289]
we would like to have a multi-node cli command manger similar to our counter manager in monitor:
- developers write a cli command
- developers select the multiple machines they want to send the cli command to, with running interval
- developers click run, and get a view where the responses from multiple machines are automatically visualized as a table (may be nested when the response in json format is nested)
- the scenario can be saved, edited and listed.

**Comment by mcfatealan** [comment]
Done in https://github.com/rDSN-Projects/rDSN.Python/pull/17, please review @imzhenyu .

**Comment by imzhenyu** [comment]
Nice work, @mcfatealan You may demo this in today's sync meeting.

**Comment by mcfatealan** [comment]
No problem, it's important to receive feedback from you~

**Comment by mcfatealan** [comment]
Feedback Note:
Put the result on the top and allow the table to hide specific items
