### ISSUE TITLE
safe_task_handle memory leak when the task is cancelled by the tracker instead of explicit safe_handle::cancel call

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#34]
TODO

**Comment by imzhenyu** [comment]
try to fix this in https://github.com/imzhenyu/rDSN/pull/75 @shengofsun @qinzuoyan @glglwty please help review.

**Comment by glglwty** [comment]
@imzhenyu It seems fine to me

**Comment by imzhenyu** [comment]
thanks @glglwty

**Comment by shengofsun** [comment]
@imzhenyu you may forgot to mofify the safe_late_task, which is also a derived class of safe_task_handle

**Comment by imzhenyu** [comment]
@shengofsun , I see. My bad, will do in the next pr.
