### ISSUE TITLE
deployment model comparion for three approaches

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#39]
(1) raw
(2) docker
(3) docker + kubernetes

**Comment by qinzuoyan** [comment]
hi, all, what the status of deploy supporting (both on windows and linux)?
and if supported, is there any document?

**Comment by imzhenyu** [comment]
@goksyli writes some documents, and he can show you guys the URL. In both cases, we are using run.cmd or run.sh in our root directory for publish, republish, deployment, start, stop, cleanup, etc.

**Comment by goksyli** [comment]
done in #150

**Comment by goksyli** [comment]
There is a [wiki](https://github.com/goksyli/rDSN/wiki/How-to-Deploy-your-rDSN-applications%28Linux-version%29) for three deployments. And welcome to comment here so that I can improve it to make it more clear.

**Comment by qinzuoyan** [comment]
Great (zan~)

**Comment by imzhenyu** [comment]
This is great - let's all try it on our own clusters and provide feedback when possible.

**Comment by imzhenyu** [comment]
comment 1: need URLs for the section introductions.

**Comment by goksyli** [comment]
@imzhenyu I don't get the meaning of "section introductions"

**Comment by imzhenyu** [comment]
I mean these:

•Section 1 for Pure Linux
•Section 2 for Docker
•Section 3 for Kubernetes

Anyway, let's do the review on pull requests, which can be much more efficient by inlining the comments.

**Comment by goksyli** [comment]
the issue is done in pr #150 

For a tutorial of three approaches of deployments, please refer [here](https://github.com/goksyli/rDSN/wiki/How-to-Deploy-your-rDSN-applications%28Linux-version%29)
