### ISSUE TITLE
determine standard of terms used in rDSN

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#40]
There are lots of terms used in rDSN code and config, and some ones are confusing. So it's necessary to make a standard. 

Terms include:
- app_id
- app_name/role_name
- role_index
- app_full_name
- app_type

**Comment by qinzuoyan** [comment]
refer to pull request: https://github.com/imzhenyu/rDSN/pull/22

**Comment by imzhenyu** [comment]
Nice. I see the pull request does not compile ok though. I cannot see the detailed logs now. Would you please take a look and make sure auto-test is ok then we can merge.

**Comment by qinzuoyan** [comment]
fixed and merged
