### ISSUE TITLE
web studio is broken due to http message parser change

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#420]
Problem:
- http request from web studio are not parsed correctly due to recent change in http message parser

Solution:
- need to change related JavaScript code as well to post the requests correctly. 
- add a test case will avoid further break.

**Comment by imzhenyu** [comment]
http://stackoverflow.com/questions/8538319/jquery-ajax-custom-http-headers-issue
Our web studio uses cross-domain js calls which does not allow custom headers. I'm changing the http message parser back to use the url. @qinzuoyan FYI.

**Comment by qinzuoyan** [comment]
OK, I see. But you'd better consider the case that an attribute is both set in url and header, but with different value. In this case, which one to choose? or treat as error?

**Comment by imzhenyu** [comment]
No worry, right now the underlying js call dsn_call is defined by us, so I'll skip considering this case at the moment.

**Comment by imzhenyu** [comment]
everything works again.
