### ISSUE TITLE
determine zookeeper client version and version compatibility between zookeeper client and server

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#43]
two things:
- determine the version of zookeeper c client to use
- check the version compatibility between zookeeper client and server

**Comment by shengofsun** [comment]
1. Currently we use the stable version of C client 3.4.6.
2. I have checked the zookeeper 3.4.6, 3.4.7 and the 3.5.1(alpha version), the protocol are kept unchanged. And in 3.5.1, there are some enhancements. So we'd better keep zookeeper c client a independent external project to make it easy to upgrade version.

**Comment by imzhenyu** [comment]
Agree. Meanwhile, we do need some approaches to check against this. E.g., when there is a failure in the zookeeper-based providers, is it possible for us to automatically get notified that the client and server version do not match and what to do next for users, etc.?

**Comment by shengofsun** [comment]
Checking if the version is matched should be done via the return-code of the zookeeper api, and we may add some test-cases to test it. 
But a better understanding on the zookeeper-server's response to the client's request is needed, as there is no error_code like "version unmatch". We may keep this issue opened, and let me consider it next year.

**Comment by qinzuoyan** [comment]
close now, will reopen it if need
