### ISSUE TITLE
Use solution folder to organize sub-projects in an IDE such as Visual Studio

### ISSUE THREAD

**Issue by linmajia** [imzhenyu/rDSN#445]
1. In top level CMakeLists.txt, add "set_property(GLOBAL PROPERTY USE_FOLDERS ON)"
2. In a sub-project's CMakeLists.txt, add "set_target_properties(${MY_PROJ_NAME} PROPERTIES FOLDER "FolderName")" after statements such as "dsn_add_static_library()"

**Comment by imzhenyu** [comment]
this is done in #448
