### ISSUE TITLE
linux install script is broken

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#450]
The script seems not working any more.

```
zhenyug@SRGSSD-06:~/projects/rDSN$ ./run.sh build
zhenyug@SRGSSD-06:~/projects/rDSN$ ./run.sh install
ERROR: not build yet
```

**Comment by qinzuoyan** [comment]
if it is not the first build time, you need not install, because "build"
will copy output files to DSN_ROOT dir.

**Comment by imzhenyu** [comment]
I understand what happened, but the message is not correct and may confuse the users.
