### ISSUE TITLE
write mutation log bug

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#476]
Both weijie and I meet the same coredump when kill replica-server repeatedly:

```
D09:23:10.588 (1468920190588449659 4ab4) replica.default0.00004a8600010001: replica.stub:204:initialize(): start to replay shared log
D09:23:10.588 (1468920190588922034 4ab4) replica.default0.00004a8600010001: mutation_log:429:open(): open shared log /home/work/ssd1/pegasus/c3tst-v4/replica/slog/log.32.785532070 succeed, start_offset = 785532070, end_offset = 819086506, size = 33554436
D09:23:10.589 (1468920190589296165 4ab4) replica.default0.00004a8600010001: mutation_log:429:open(): open shared log /home/work/ssd1/pegasus/c3tst-v4/replica/slog/log.33.819086506 succeed, start_offset = 819086506, end_offset = 852641112, size = 33554606
D09:23:10.591 (1468920190591251145 4ab4) replica.default0.00004a8600010001: mutation_log:429:open(): open shared log /home/work/ssd1/pegasus/c3tst-v4/replica/slog/log.34.852641112 succeed, start_offset = 852641112, end_offset = 880403431, size = 27762319
D09:23:10.591 (1468920190591542694 4ab4) replica.default0.00004a8600010001: mutation_log:710:replay(): start to replay mutation log /home/work/ssd1/pegasus/c3tst-v4/replica/slog/log.32.785532070, offset = [785532070, 819086506), size = 33554436
E09:23:11.119 (1468920191119837061 4ab4) replica.default0.00004a8600010001: mutation_log:1818:read_next_log_block(): crc checking failed
D09:23:11.119 (1468920191119878881 4ab4) replica.default0.00004a8600010001: mutation_log:766:replay(): finish to replay mutation log /home/work/ssd1/pegasus/c3tst-v4/replica/slog/log.32.785532070, err = ERR_INVALID_DATA
E09:23:11.119 (1468920191119910844 4ab4) replica.default0.00004a8600010001: mutation_log:883:replay(): replay mutation log failed: ERR_INVALID_DATA
E09:23:11.119 (1468920191119976007 4ab4) replica.default0.00004a8600010001: replica.stub:244:initialize(): replay shared log failed, err = ERR_INVALID_DATA, time_used = 531 ms, clear all logs ...
W09:23:11.121 (1468920191121356995 4ab4) replica.default0.00004a8600010001: dsn.file_utils:640:rename_path(): rename from '/home/work/ssd5/pegasus/c3tst-v4/replica/reps/1.5.rrdb' to '/home/work/ssd5/pegasus/c3tst-v4/replica/reps/1.5.rrdb.err' failed, err = Directory not empty
F09:23:11.121 (1468920191121372573 4ab4) replica.default0.00004a8600010001: /home/work/pegasus/rDSN/src/dist/replication/lib/replica_stub.cpp:261:initialize(): assertion expression: false
F09:23:11.121 (1468920191121381780 4ab4) replica.default0.00004a8600010001: /home/work/pegasus/rDSN/src/dist/replication/lib/replica_stub.cpp:261:initialize(): we cannot recover from the above error, exit ...
```

We doubt  it is caused by unprotected concurrent write of mutation log.
@imzhenyu , would you please look into it?

**Comment by qinzuoyan** [comment]
@imzhenyu , as I said yesterday, there may be some bugs brought by recent refactor. We need to make it as stable as v0.95 ASAP.

**Comment by imzhenyu** [comment]
I will take a look tomorrow. The refactor to the mutation log is inevitable as our performance profiling reveals that the lock used in the shared log (removed after refactoring) is a source of lock contention. As for the concurrent write, as long as the lock offset assignment is protected, concurrent writes should be fine. I'll see whether it is caused by other problems.

**Comment by shengofsun** [comment]
@imzhenyu although the offset is assigned in protection, the crc in shared log is not. The code is as follows(log_file::commit_log_block): 

```
hdr->body_crc = _crc32;
auto vec_size = (int)block.data().size();
dsn_file_buffer_t* buffer_vector = (dsn_file_buffer_t*)alloca(sizeof(dsn_file_buffer_t) * vec_size);
for (int i = 0; i < vec_size; i++)
{
    auto & blk = block.data()[i];
    buffer_vector[i].buffer = reinterpret_cast<void*>(const_cast<char*>(blk.data()));
    buffer_vector[i].size = blk.length(); 

    // skip block header
    if (i > 0)
    {
        hdr->body_crc = dsn_crc32_compute(
            static_cast<const void*>(blk.data()),
            static_cast<size_t>(blk.length()), hdr->body_crc
            );
    }        
}
_crc32 = hdr->body_crc;
```

if two threads execute concurrently, I think the crc32 may be updated mistakenly. 

Another issue is that I suspect that the order of offset assignment and the order of disk io may be inconsistent, for example:
mutation A in thread A1 got a offset of A2
mutation B in thread B1 got a offset of B2, 
is it possible that A2 < B2, but mutation B is append earlier than mutation A in the log?
In this case, the crc check may also fail.

**Comment by imzhenyu** [comment]
Right, now we use chain crc!!! One quick fix is to use stand-alone crc for each call as done in the old times. You may need to fix the replay part as well.

**Comment by imzhenyu** [comment]
As for the second issue, it is possible that the later offset io is completed first, which may lead to holes in the log ... I think my previous optimization is too aggressive, which leads to checking failure during replay. I'll fix this tomorrow.

**Comment by qinzuoyan** [comment]
@imzhenyu , are you fixing the bug?
I think we need to fix the two problem:
- crc should be local variable, and should not be chain crc (which will depend on class variable)
- we get the file offset protected by lock in mark_new_update(), and then do something without lock (computing crc, etc), and finally put aio_task in work queue by invoking work_queue::add_work() to serial write operation. But the problem is: the scheduling order of mark_new_update() may be not same with the scheduling order of work_queue::add_work(), which will cause offset not correct.

**Comment by shengofsun** [comment]
I'm fixing the chained crc problem, and now running the kill test.

**Comment by imzhenyu** [comment]
@qinzuoyan @shengofsun I'm working on it.
- chain crc is good as it helps protect the data integrity with stronger guarantee (not only the current block, but also the sequence in a log file). however, the current implementation does not guarantee that the chain crc is computed in sequence (have race).
- offset is always assigned ok. The fatal issue is that the blocks with larger offsets may be written first while the early block is never written as the process crashes at this exact point. In this case, there will be holes in the share log and lead to replay failure.

Conclusion, for now, I'm falling back the single write mode for the share log. It will scarify the performance and we can see how to improve it further. What do you think?

**Comment by qinzuoyan** [comment]
I don't understand the sentence of "offset is always assigned ok". I think it may cause problem even not under the fatal issue: the blocks with larger offset may be written before the blocks with smaller offset, then the offset set in data is not matched with the real offset in file.

**Comment by imzhenyu** [comment]
@qinzuoyan We use the async mode to write, and specify the offset explicitly when calling write. Thereafter, it is possible that the file range [200, 300) is written while [0, 200) is undefined.

**Comment by qinzuoyan** [comment]
@imzhenyu , if as you say, then we break the sequence write model...

**Comment by imzhenyu** [comment]
@qinzuoyan Exactly.

**Comment by shengofsun** [comment]
@imzhenyu but performance for random access of disk is not as good as sequence write.

**Comment by shengofsun** [comment]
BTW, I think standalone crc should be enough for hardware fault.

**Comment by imzhenyu** [comment]
@shengofsun Yes, I was counting on the auto-batch layer in disk engine to turn this into sequential write in most cases (because the offsets are clearly conforming the sequential writing pattern). But since we have issues now at the upper layer, we need to do the batching and sequencing by ourselves.

**Comment by qinzuoyan** [comment]
@imzhenyu , to resolve the log hole problem, I considered these ways:
- first way: determine the offset in lock, and invoke file::write() in the same lock. That is, we delay setting offset to log_file::commit_log_block() just before invoking file::write_vector() and protected them in the same lock range. It will scarify the performance, but because computing crc is not in lock, the lock contention is small.
- second way: we add a callback in aio_task, when process_write(), the callback is invoked, which will set the offset of the aio_task and mutation_data.

Both the ways will ensure sequence write.

**Comment by imzhenyu** [comment]
@qinzuoyan @shengofsun Just finish the rough fix, did not test yet. You may have a look first, and I will continue the testing. 
https://github.com/imzhenyu/rDSN/commit/3764b404a9acf99c0ee7726509f4a9e7a9af1423

**Comment by qinzuoyan** [comment]
@imzhenyu , what's the idea behind the code?

**Comment by imzhenyu** [comment]
Simply fall back to the single write mode, but putting the `log_file::commit_log_block` explicitly outside the lock. Crc is remain unchanged as now there is only one concurrent write permitted.

**Comment by qinzuoyan** [comment]
I'll summit our kill-test code to rrdb, then you can also run kill-test to find bugs.

**Comment by imzhenyu** [comment]
Sure, thanks.
