### ISSUE TITLE
load module ordering problem

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#489]
Now that modules are specified in config [modules] and loaded at runtime, the loading order is meaningful.

For example, I specify modules as:

```
[modules]
dsn.tools.common
dsn.dist.providers.common
```

Generally I expect the loading order is the same as appearing order specified in config. But because we use map to store data in _configuration_ class, the modules are loaded in **alphabetical order**, which may cause some unexpected problems, such as:

```
task_spec:101:register_task_code():overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX from THREAD_POOL_META_SERVER to THREAD_POOL_DEFAULT
task_spec:101:register_task_code():overwrite default thread pool for task RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX_ACK from THREAD_POOL_META_SERVER to THREAD_POOL_DEFAULT
service_api_main:216:load_all_modules():load shared library dsn.dist.providers.common successfully
service_api_main:216:load_all_modules():load shared library dsn.tools.common successfully
```

In module _dsn.tools.common_, RPC_CM_QUERY_PARTITION_CONFIG_BY_INDEX is bind to THREAD_POOL_DEFAULT, but in module _dsn.dist.providers.common_ we expect to rebind it to  THREAD_POOL_META_SERVER. For the reason of improper loading order, we get an unexpected result.

**Comment by qinzuoyan** [comment]
Another problem is, if some task codes are bind to different task pool in different modules, then the real binding is determined by the config order, which increases configuring difficulty for user, and in worse, it may bring in unsolvable conflict.

**Comment by imzhenyu** [comment]
@qinzuoyan The task code re-binding is now done through auto-init global symbols. However, it is not reliable on Linux as Linux always references the same symbol even the symbol is redefined in the current .so. On the other hand, I've thought about the library order problem before, and my previous thinking is that a good design should decouple these modules so that their order does not matter.  There are two possible solutions:
- always relying on configuration file to get the task code binding correct
- (1) move task code hard binding to dsn_module_init; (2) ensure library loading order according to the given order in config file.

**Comment by qinzuoyan** [comment]
@imzhenyu , actually #513 is not enough. In function load_all_modules(), it firstly load modules in [modules], and then modules in [apps.xxx].dmodule. That means, app dmodules can only be loaded after [modules], so the order is not so meaningful...

**Comment by imzhenyu** [comment]
You can move all modules to the (modules) section if order matters, the  apps module is there just coz I don't want to break existing config files.

**Comment by qinzuoyan** [comment]
Or we can check that the module specified by dmodule must appear in [modules].

?$B<+2fE*(B iPhone

$B:_(B 2016$BG/(B8$B7n(B4$BF|!$(B00:49$B!$(BZhenyu Guo <notifications@github.com<mailto:notifications@github.com>> $B<LF;!'(B

You can move all modules to the (modules) section if order matters, the apps module is there just coz I don't want to break existing config files.

##

**Comment by imzhenyu** [comment]
Close now since it is done.
