### ISSUE TITLE
query interface in perf_counters for the current value of any counter  for real-time visualization

### ISSUE THREAD

**Issue by mcfatealan** [imzhenyu/rDSN#56]

**Comment by imzhenyu** [comment]
this interface should be registered in perf_counters instead of profiler, as some counters may not related to profiling at all.

**Comment by mcfatealan** [comment]
At this moment it's temporarily added in profiling_command

**Comment by imzhenyu** [comment]
we need to move it to perf_counters then; otherwise the semantic is incorrect.

**Comment by mcfatealan** [comment]
Done.
