### ISSUE TITLE
rdsn deployment using kubernetes

### ISSUE THREAD

**Issue by goksyli** [imzhenyu/rDSN#68]
First, we should deploy replication servers and one meta server separately on kubernetes cluster. Just one `service-app` per process and test them. 

For **consistent access IP**, we should associate them each with one `kubernetes service`. So that despite of failover from them, these servers can have unchanged **accessible ip**.

**Comment by goksyli** [comment]
Path to checkpoints and logs of meta-server and replication server are not configurable currently, I think.
That makes it difficult to write [kubernetes pod spec](https://github.com/kubernetes/kubernetes/blob/master/examples/rethinkdb/admin-pod.yaml), since they are in the same directory as the program now.

**Comment by imzhenyu** [comment]
this path issue is fixed in pr https://github.com/imzhenyu/rDSN/pull/74

**Comment by imzhenyu** [comment]
the consistent IP issue is fixed (from rdsn side) in pr https://github.com/imzhenyu/rDSN/pull/60

**Comment by goksyli** [comment]
done in #150

**Comment by goksyli** [comment]
the issue is done in pr #150 
For a tutorial of easy creation a kubernetes, please refer [here](https://github.com/goksyli/rDSN/wiki/A-easy-walkthrough-for-setting-up-a-Kubernetes-cluster-on-Ubuntu%28-multinodes-%29)

For a tutorial of kubernetes deployments, please refer [here](https://github.com/goksyli/rDSN/wiki/How-to-Deploy-your-rDSN-applications%28Linux-version%29#3-deployment-on-kubernetes)
