### ISSUE TITLE
change dlopen flag in Linux/FreeBSD/OSX to make symbols available for python interpreter 

### ISSUE THREAD

**Issue by mcfatealan** [imzhenyu/rDSN#72]
implemented by #66

**Comment by imzhenyu** [comment]
pr merged, but there is a still an TODO issue for this fix, as concerned by @qinzuoyan . Let's keep this as a TODO.

**Comment by mcfatealan** [comment]
okay

**Comment by mcfatealan** [comment]
Since there's no further action, I'll close it now.
