### ISSUE TITLE
make path to logs and checkpoint configurable  

### ISSUE THREAD

**Issue by goksyli** [imzhenyu/rDSN#73]
Currently, path to logs and checkpoints are by default the same directory as program and can't be configurable. That make it difficult to put them on persistent volumes when deployment on cluster

**Comment by imzhenyu** [comment]
work on this now.

**Comment by goksyli** [comment]
thx :+1:

**Comment by imzhenyu** [comment]
implemented in https://github.com/imzhenyu/rDSN/pull/74  please help review. @goksyli @qinzuoyan

**Comment by imzhenyu** [comment]
result data dir convention:

[core] data_dir defines the root data directory
 ${data_dir}/coredump for coredumps
 ${data_dir}/logs for all logs
 ${data_dir}/${app_name} for all apps data dir
