### ISSUE TITLE
cleanup the scripts in the top directory

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#79]
Trying to add scripts for the windows platform. But there are now too many scripts in the top directory already. Let's have a top dispatcher command and move these existing ones into subdirectory. E.g.,

/run.sh|run.cmd pre-require|build|install|test|test_cov|start_zk|stop_zk

all scripts go to:
/scripts/${os}/xxx.sh|.cmd

What do you guys think about this?

**Comment by imzhenyu** [comment]
@qinzuoyan

**Comment by imzhenyu** [comment]
we also need a single point to setup the DSN_ROOT env var for installation and inquiry from other projects. run.cmd|.sh provides such a single point for testing and setup.

**Comment by qinzuoyan** [comment]
Nice, I agree with it. So let's do it, I write the scripts on linux, and you write the scripts on windows, ok?

**Comment by imzhenyu** [comment]
Good. that's exactly what I @ you for:)

**Comment by imzhenyu** [comment]
seems GitHub does not support assigning issue to multiple persons

**Comment by imzhenyu** [comment]
anyway, i'm working on the windows version, so this issue will stay opened

**Comment by imzhenyu** [comment]
integrate deployment scripts as well into run.cmd|.sh https://github.com/imzhenyu/rDSN/issues/85
@goksyli  is working on Linux version, will be integrated into this run.sh too.

**Comment by imzhenyu** [comment]
intergrate start_zk and stop_zk into run.cmd
