### ISSUE TITLE
add multiple app launch support in args 

### ISSUE THREAD

**Issue by mcfatealan** [imzhenyu/rDSN#94]
At present we use this to choose which app to run

``` bash
.\dsn.replication.simple_kv.exe config.ini -app meta -app_index 1
```

what if we want to add one more app `monitor`?

We want to support this usage:

``` bash
.\dsn.replication.simple_kv.exe config.ini -app meta;monitor -app_index 1
```

**Comment by qinzuoyan** [comment]
but what about app_index? maybe this way:

```
.\dsn.replication.simple_kv.exe config.ini -app_list meta@1,monitor
```

"meta@1" means app=meta, app_index=1
"monitor" means app=monitor, app_index=all

**Comment by imzhenyu** [comment]
I like @qinzuoyan 's proposal, which seems better than what we just discussed @mcfatealan

**Comment by mcfatealan** [comment]
Good! Actually I just finished the last version..... let me alter to the new usage.

**Comment by mcfatealan** [comment]
Done.
