### ISSUE TITLE
deploy.sh is still specific to the target application

### ISSUE THREAD

**Issue by goksyli** [imzhenyu/rDSN#99]
currently `deploy.sh` need to invoke `deploy.<deployment_name>.sh`. We need to make this more general.
And the `start.sh` need runtime info to run, which is difficult for local sysadmin to debug. We need to remove this runtime info requirement.

**Comment by goksyli** [comment]
done in #100 @imzhenyu please review

**Comment by imzhenyu** [comment]
@goksyli , we need to make the issue more meaningful - the current title does not reveal the issue or the purpose.
